[tools]
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
selene = "kampfkarren/selene@0.28.0"
rojo = "rojo-rbx/rojo@7.4.4"
luau-lsp = "JohnnyMorganz/luau-lsp@1.38.0"
stylua = "JohnnyMorganz/StyLua@2.0.2"
pseudo-enum = "nightcycle/pseudo-enum@1.0.5"
file-to-luau = "nightcycle/file-to-luau@1.0.0"
file-util = "nightcycle/file-util@0.1.2"
darklua = "seaofvoices/darklua@0.15.0"
lune = "lune-org/lune@0.8.9"
